// --- App State ---
let quizData = null;
let currentQuestions = [];
let currentQuestionIndex = 0;
let currentQuizId = ''; 
let userProgress = JSON.parse(localStorage.getItem('gkgsProgress')) || {};

const SETS_PER_WEEK = 6;

// --- DOM Elements ---
const views = {
    main: document.getElementById('main-menu-view'),
    sub: document.getElementById('sub-menu-view'),
    quiz: document.getElementById('quiz-view')
};

const weeksGrid = document.getElementById('weeks-grid');
const daysGrid = document.getElementById('days-grid');
const weekTitle = document.getElementById('week-title');

const questionText = document.getElementById('question-text');
const optionsContainer = document.getElementById('options-container');
const prevBtn = document.getElementById('prev-btn');
const nextBtn = document.getElementById('next-btn');
const progressText = document.getElementById('progress-text');
const progressBarFill = document.getElementById('progress-bar-fill');

// --- Initialization ---
async function initApp() {
    try {
        // Fetches the JSON file generated by the python script
        const response = await fetch('quiz_sets.json');
        quizData = await response.json();
        renderMainMenu();
    } catch (error) {
        console.error("Error loading quiz data:", error);
        weeksGrid.innerHTML = `<p style="color:red;">Failed to load quiz_sets.json. Please ensure you are running this through a local web server (like VS Code Live Server) and not just double-clicking the HTML file.</p>`;
    }
}

// --- View Navigation ---
function switchView(viewName) {
    Object.values(views).forEach(view => view.classList.remove('active'));
    views[viewName].classList.add('active');
}

// --- Progress Helpers ---
function saveProgress() {
    localStorage.setItem('gkgsProgress', JSON.stringify(userProgress));
}

function getProgressStats(quizId, totalQuestions) {
    const prog = userProgress[quizId] || { answers: {} };
    const answered = Object.keys(prog.answers).length;
    return {
        answered,
        total: totalQuestions,
        percent: totalQuestions > 0 ? (answered / totalQuestions) * 100 : 0,
        completed: answered === totalQuestions && totalQuestions > 0,
        answers: prog.answers
    };
}

function generateProgressBarHTML(percent, completed) {
    const fillClass = completed ? 'card-progress-fill completed' : 'card-progress-fill';
    return `
        <div class="card-progress-container">
            <div class="${fillClass}" style="width: ${percent}%"></div>
        </div>
    `;
}

// --- Main Menu (Weeks) ---
function renderMainMenu() {
    switchView('main');
    weeksGrid.innerHTML = '';
    
    const totalSets = quizData.metadata.total_sets;
    const totalWeeks = Math.ceil(totalSets / SETS_PER_WEEK);
    
    for (let w = 1; w <= totalWeeks; w++) {
        // Calculate total progress for the week
        let weekAnswered = 0;
        let weekTotalQuestions = 0;
        
        // Days 1-6
        for(let d = 1; d <= 6; d++) {
            const setIndex = (w - 1) * SETS_PER_WEEK + d;
            const setId = `set_${setIndex}`;
            if (quizData.sets[setId]) {
                const dayTotal = quizData.sets[setId].length;
                weekTotalQuestions += dayTotal;
                weekAnswered += getProgressStats(setId, dayTotal).answered;
            }
        }
        
        // Day 7 Revision stats
        const revId = `rev_week_${w}`;
        const revTotal = weekTotalQuestions; // Revision is sum of days 1-6
        weekTotalQuestions += revTotal;
        weekAnswered += getProgressStats(revId, revTotal).answered;

        const percent = weekTotalQuestions > 0 ? (weekAnswered / weekTotalQuestions) * 100 : 0;
        const completed = weekAnswered === weekTotalQuestions && weekTotalQuestions > 0;

        const card = document.createElement('div');
        card.className = 'menu-card';
        card.innerHTML = `
            <h3>Week ${w}</h3>
            <p style="font-size: 0.8rem; margin-top: 5px;">${weekAnswered} / ${weekTotalQuestions}</p>
            ${generateProgressBarHTML(percent, completed)}
        `;
        card.onclick = () => renderSubMenu(w, totalSets);
        weeksGrid.appendChild(card);
    }
}

// --- Sub Menu (Days) ---
function renderSubMenu(weekNum, totalSets) {
    switchView('sub');
    weekTitle.innerText = `Week ${weekNum}`;
    daysGrid.innerHTML = '';
    
    let revisionQuestions = [];

    // Days 1-6
    for (let d = 1; d <= 6; d++) {
        const setIndex = (weekNum - 1) * SETS_PER_WEEK + d;
        if (setIndex > totalSets) break; // Reached the end of available sets
        
        const setId = `set_${setIndex}`;
        const questions = quizData.sets[setId];
        revisionQuestions = revisionQuestions.concat(questions);
        
        createDayCard(`Day ${d}`, setId, questions, () => startQuiz(setId, questions));
    }
    
    // Day 7 (Revision)
    if (revisionQuestions.length > 0) {
        const revId = `rev_week_${weekNum}`;
        createDayCard('Day 7 (Revision)', revId, revisionQuestions, () => startQuiz(revId, revisionQuestions));
    }
}

function createDayCard(title, quizId, questionsArr, onClickCallback) {
    const totalQ = questionsArr.length;
    const stats = getProgressStats(quizId, totalQ);
    
    const card = document.createElement('div');
    card.className = 'menu-card';
    card.innerHTML = `
        <h3>${title}</h3>
        <p style="font-size: 0.8rem; margin-top: 5px;">${stats.answered} / ${stats.total}</p>
        ${generateProgressBarHTML(stats.percent, stats.completed)}
    `;
    card.onclick = onClickCallback;
    daysGrid.appendChild(card);
}

// --- Quiz Logic ---
function startQuiz(quizId, questionsArr) {
    currentQuizId = quizId;
    currentQuestions = questionsArr;
    currentQuestionIndex = 0;
    
    if (!userProgress[currentQuizId]) {
        userProgress[currentQuizId] = { answers: {} };
    }
    
    switchView('quiz');
    updateQuizHeader();
    renderQuestion();
}

function updateQuizHeader() {
    const stats = getProgressStats(currentQuizId, currentQuestions.length);
    progressText.innerText = `${stats.answered} / ${stats.total}`;
    progressBarFill.style.width = `${stats.percent}%`;
    
    if (stats.completed) {
        progressBarFill.classList.add('completed');
    } else {
        progressBarFill.classList.remove('completed');
    }
}

function renderQuestion() {
    const q = currentQuestions[currentQuestionIndex];
    questionText.innerText = `Q${currentQuestionIndex + 1}. ${q.question}`;
    optionsContainer.innerHTML = '';

    const answersState = userProgress[currentQuizId].answers;
    const previouslyAnsweredKey = answersState[currentQuestionIndex];
    const isAnswered = previouslyAnsweredKey !== undefined;

    // Render options
    for (const [key, text] of Object.entries(q.options)) {
        const btn = document.createElement('button');
        btn.className = 'option-btn';
        btn.innerText = `${key.toUpperCase()}. ${text}`;
        
        if (isAnswered) {
            btn.disabled = true;
            // Highlight logic for previously answered
            if (key === q.answer.key) {
                btn.classList.add('correct'); // Correct always shows green
            } else if (key === previouslyAnsweredKey && key !== q.answer.key) {
                btn.classList.add('wrong'); // Picked wrong, show red
            }
        } else {
            btn.onclick = () => handleOptionClick(key, q.answer.key);
        }
        
        optionsContainer.appendChild(btn);
    }

    // Button states
    prevBtn.disabled = currentQuestionIndex === 0;
    nextBtn.disabled = currentQuestionIndex === currentQuestions.length - 1;
}

function handleOptionClick(selectedKey, correctKey) {
    // Record answer
    userProgress[currentQuizId].answers[currentQuestionIndex] = selectedKey;
    saveProgress();
    updateQuizHeader();

    // Re-render to show colors and disable buttons
    renderQuestion();
}

// --- Event Listeners ---
document.getElementById('return-to-main').addEventListener('click', renderMainMenu);
document.getElementById('return-to-sub').addEventListener('click', () => {
    // Determine which week we were on by checking currentQuizId
    // format: set_15 or rev_week_3
    let weekNum = 1;
    if (currentQuizId.startsWith('rev_week_')) {
        weekNum = parseInt(currentQuizId.replace('rev_week_', ''));
    } else if (currentQuizId.startsWith('set_')) {
        const setIndex = parseInt(currentQuizId.replace('set_', ''));
        weekNum = Math.ceil(setIndex / SETS_PER_WEEK);
    }
    renderSubMenu(weekNum, quizData.metadata.total_sets);
});

prevBtn.addEventListener('click', () => {
    if (currentQuestionIndex > 0) {
        currentQuestionIndex--;
        renderQuestion();
    }
});

nextBtn.addEventListener('click', () => {
    if (currentQuestionIndex < currentQuestions.length - 1) {
        currentQuestionIndex++;
        renderQuestion();
    }
});

// Boot the app
window.addEventListener('DOMContentLoaded', initApp);